env:
  node: true
  es2020: true
  

rules:
  no-console: 0
  import/extensions: 0
  linebreak-style: 0
  no-eval: 0
  
extends:
  - airbnb-base

parserOptions:
  ecmaVersion: 11
  sourceType: module
